# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'articulo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(371, 316)
        MainWindow.setMinimumSize(QtCore.QSize(371, 316))
        MainWindow.setMaximumSize(QtCore.QSize(371, 316))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #f4f3ee;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: bold 16px;\n"
"     color: #434343;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: white;\n"
"    font: bold 14px;\n"
"     color: #434343;\n"
"    border: 0.5px solid gray;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: bold 16px;\n"
"    border: 0.5px solid #f4f3ee;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbOption = QtWidgets.QComboBox(self.centralwidget)
        self.cbOption.setGeometry(QtCore.QRect(130, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cbOption.setFont(font)
        self.cbOption.setStyleSheet("background-color: white;")
        self.cbOption.setMaxVisibleItems(3)
        self.cbOption.setObjectName("cbOption")
        self.cbOption.addItem("")
        self.cbOption.addItem("")
        self.cbOption.addItem("")
        self.btnAceptar = QtWidgets.QPushButton(self.centralwidget)
        self.btnAceptar.setGeometry(QtCore.QRect(144, 270, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnAceptar.setFont(font)
        self.btnAceptar.setStyleSheet("background-color: #70d6ff;")
        self.btnAceptar.setObjectName("btnAceptar")
        self.lbID = QtWidgets.QLabel(self.centralwidget)
        self.lbID.setGeometry(QtCore.QRect(20, 110, 81, 31))
        self.lbID.setObjectName("lbID")
        self.lbName = QtWidgets.QLabel(self.centralwidget)
        self.lbName.setGeometry(QtCore.QRect(20, 160, 81, 31))
        self.lbName.setObjectName("lbName")
        self.lbPrice = QtWidgets.QLabel(self.centralwidget)
        self.lbPrice.setGeometry(QtCore.QRect(20, 210, 81, 31))
        self.lbPrice.setObjectName("lbPrice")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(120, 110, 221, 31))
        self.txtID.setText("")
        self.txtID.setObjectName("txtID")
        self.txtName = QtWidgets.QLineEdit(self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(120, 160, 221, 31))
        self.txtName.setObjectName("txtName")
        self.txtPrice = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPrice.setGeometry(QtCore.QRect(120, 210, 221, 31))
        self.txtPrice.setObjectName("txtPrice")
        self.lbMSG = QtWidgets.QLabel(self.centralwidget)
        self.lbMSG.setGeometry(QtCore.QRect(20, 70, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lbMSG.setFont(font)
        self.lbMSG.setStyleSheet("font: bold 13px;")
        self.lbMSG.setAlignment(QtCore.Qt.AlignCenter)
        self.lbMSG.setObjectName("lbMSG")
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setGeometry(QtCore.QRect(10, 10, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btnBack.setFont(font)
        self.btnBack.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnBack.setStyleSheet("border-radius: 15px;\n"
"background-color: #25b7d3;\n"
"")
        self.btnBack.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/backB.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBack.setIcon(icon)
        self.btnBack.setIconSize(QtCore.QSize(28, 28))
        self.btnBack.setObjectName("btnBack")
        self.cbID = QtWidgets.QComboBox(self.centralwidget)
        self.cbID.setEnabled(True)
        self.cbID.setGeometry(QtCore.QRect(120, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(60)
        self.cbID.setFont(font)
        self.cbID.setStyleSheet("background-color: white;")
        self.cbID.setObjectName("cbID")
        MainWindow.setCentralWidget(self.centralwidget)

        self.txtPrice.setValidator(QtGui.QDoubleValidator())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Admin"))
        self.cbOption.setCurrentText(_translate("MainWindow", "Agregar"))
        self.cbOption.setItemText(0, _translate("MainWindow", "Agregar"))
        self.cbOption.setItemText(1, _translate("MainWindow", "Modificar"))
        self.cbOption.setItemText(2, _translate("MainWindow", "Eliminar"))
        self.btnAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.btnAceptar.setShortcut(_translate("MainWindow", "Return"))
        self.lbID.setText(_translate("MainWindow", "ID:"))
        self.lbName.setText(_translate("MainWindow", "Nombre:"))
        self.lbPrice.setText(_translate("MainWindow", "Precio $:"))
        self.lbMSG.setText(_translate("MainWindow", "Ingrese los datos requeridos"))
        self.btnBack.setShortcut(_translate("MainWindow", "Esc"))
