# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 224)
        MainWindow.setMinimumSize(QtCore.QSize(271, 224))
        MainWindow.setMaximumSize(QtCore.QSize(271, 224))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #f4f3ee;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: white;\n"
"    border: 0.5px solid gray;\n"
"    border-radius: 5px;\n"
"    color: #434343;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: #70d6ff;\n"
"    border: 0.5px solid #edf6f9 ;\n"
"    border-radius: 5px;\n"
"    color: white;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: #434343;\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btnLog = QtWidgets.QPushButton(self.centralwidget)
        self.btnLog.setGeometry(QtCore.QRect(100, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnLog.setFont(font)
        self.btnLog.setObjectName("btnLog")
        self.txtUser = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUser.setGeometry(QtCore.QRect(60, 80, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.txtUser.setFont(font)
        self.txtUser.setInputMask("")
        self.txtUser.setMaxLength(12)
        self.txtUser.setPlaceholderText("USER")
        self.txtUser.setObjectName("txtUser")
        self.txtPass = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPass.setGeometry(QtCore.QRect(60, 130, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.txtPass.setFont(font)
        self.txtPass.setInputMask("")
        self.txtPass.setMaxLength(12)
        self.txtPass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPass.setPlaceholderText("PASSWORD")
        self.txtPass.setObjectName("txtPass")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "LOGIN ☺"))
        self.btnLog.setText(_translate("MainWindow", "LOGIN"))
        self.btnLog.setShortcut(_translate("MainWindow", "Return"))
